

export const DELETE_DISTRICTS = "DELETE_DISTRICTS"

export const AREAS = "AREAS"

export const PRESET_DISTRICTS = "PRESET/DISTRICTS"

export const ADD_PRODUCT = "CART/ADD_PRODUCT"
export const REMOVE_PRODUCT = "CART/REMOVE_PRODUCT"
export const REDUCE_PRODUCT = "CART/REDUCE_PRODUCT"
export const NEW_STATE = "CART/NEW_STATE"
